# Generated by Django 4.2.6 on 2023-10-26 04:17

import container.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner1', models.ImageField(upload_to=container.models.Banner.get_banner1_upload_path)),
                ('Banner2', models.ImageField(upload_to=container.models.Banner.get_banner2_upload_path)),
                ('Banner3', models.ImageField(upload_to=container.models.Banner.get_banner3_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=15)),
                ('ingredient_url', models.ImageField(null=True, upload_to='ingredient_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('receipe_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipe_title', models.CharField(max_length=15)),
                ('Description', models.TextField()),
                ('Prep_time', models.DecimalField(decimal_places=1, max_digits=5)),
                ('cook_time', models.DecimalField(decimal_places=1, max_digits=5)),
                ('serving_quantity', models.IntegerField(verbose_name=2)),
                ('categoryImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ReceipeCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.receipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('update_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=30)),
                ('receipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_identity', to='container.receipe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=10)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_detail', to='container.ingredient')),
                ('receipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_receipe', to='container.receipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipe_unit', to='container.unit')),
            ],
        ),
        migrations.AddField(
            model_name='receipe',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipe_category', to='container.receipecategory'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('procedure_number', models.PositiveIntegerField()),
                ('receipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_receipe', to='container.receipe')),
            ],
            options={
                'unique_together': {('receipe_id', 'procedure_number')},
            },
        ),
    ]
