# Generated by Django 4.2.6 on 2023-11-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_url',
            field=models.ImageField(default='path/to/default/image.jpg', null=True, upload_to='ingredient_images/'),
        ),
    ]
